<a href="https://colab.research.google.com/github/HuzaifaZia553/CUSTOMER-CHURN-RISK-ANALYSIS-FOR-A-TELECOM-COMPANY/blob/main/HR_Employee_Attrition_%E2%80%93_Advanced_Machine_Learning_Model_Comparison_%26_Optimizationipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Libraries

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# Load dataset

In [2]:
df = pd.read_csv("/content/HR_comma_sep.csv")

print(df.head())
print(df.shape)
print(df.info())

   satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157
1                0.80             0.86               5                   262
2                0.11             0.88               7                   272
3                0.72             0.87               5                   223
4                0.37             0.52               2                   159

   time_spend_company  Work_accident  left  promotion_last_5years Department  \
0                   3              0     1                      0      sales
1                   6              0     1                      0      sales
2                   4              0     1                      0      sales
3                   5              0     1                      0      sales
4                   3              0     1                      0      sales

   salary
0     low
1  medium
2  medium
3     low
4     low
(14999, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   satisfaction_level     14999 non-null  float64
 1   last_evaluation        14999 non-null  float64
 2   number_project         14999 non-null  int64
 3   average_montly_hours   14999 non-null  int64
 4   time_spend_company     14999 non-null  int64
 5   Work_accident          14999 non-null  int64
 6   left                   14999 non-null  int64
 7   promotion_last_5years  14999 non-null  int64
 8   Department             14999 non-null  object
 9   salary                 14999 non-null  object
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB
None

# Data understanding

In [3]:
print(df.describe())
print('_____________')

print(df.isnull().sum())
print('_____________')
print(df["left"].value_counts())

       satisfaction_level  last_evaluation  number_project  \
count        14999.000000     14999.000000    14999.000000
mean             0.612834         0.716102        3.803054
std              0.248631         0.171169        1.232592
min              0.090000         0.360000        2.000000
25%              0.440000         0.560000        3.000000
50%              0.640000         0.720000        4.000000
75%              0.820000         0.870000        5.000000
max              1.000000         1.000000        7.000000

       average_montly_hours  time_spend_company  Work_accident          left  \
count          14999.000000        14999.000000   14999.000000  14999.000000
mean             201.050337            3.498233       0.144610      0.238083
std               49.943099            1.460136       0.351719      0.425924
min               96.000000            2.000000       0.000000      0.000000
25%              156.000000            3.000000       0.000000      0.000000
50%              200.000000            3.000000       0.000000      0.000000
75%              245.000000            4.000000       0.000000      0.000000
max              310.000000           10.000000       1.000000      1.000000

       promotion_last_5years
count           14999.000000
mean                0.021268
std                 0.144281
min                 0.000000
25%                 0.000000
50%                 0.000000
75%                 0.000000
max                 1.000000
_____________
satisfaction_level       0
last_evaluation          0
number_project           0
average_montly_hours     0
time_spend_company       0
Work_accident            0
left                     0
promotion_last_5years    0
Department               0
salary                   0
dtype: int64
_____________
left
0    11428
1     3571
Name: count, dtype: int64

# Target variables

In [4]:
y = df["left"]

X = df.drop("left", axis=1)


#Identitify feature

In [5]:
# Numerical
numeric_features = [
    'satisfaction_level',
    'last_evaluation',
    'number_project',
    'average_montly_hours',
    'time_spend_company'
]

In [6]:
categorical_features = [
    'Department',
    'salary'
]

In [7]:
# binary
binary_features =[

'Work_accident'
'promotion_last_5years'
]

# Preprocessing pipline

In [8]:
# Numeric pipeline
numeric_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

In [9]:
# Catagorical pipline
categorical_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

In [10]:
# columns
preprocessor = ColumnTransformer([
    ('num', numeric_transformer, numeric_features),
    ('cat', categorical_transformer, categorical_features)
], remainder='passthrough')

# Train test split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

#  Model building
 ## Logestic Regression

In [12]:
log_model = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression())
])

log_model.fit(X_train, y_train)

y_pred = log_model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.92      0.87      2294
           1       0.57      0.33      0.42       706

    accuracy                           0.78      3000
   macro avg       0.69      0.63      0.64      3000
weighted avg       0.76      0.78      0.76      3000

# SVM

In [13]:
svm_model = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', SVC())
])

svm_model.fit(X_train, y_train)

y_pred = svm_model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.98      0.98      2294
           1       0.95      0.90      0.92       706

    accuracy                           0.96      3000
   macro avg       0.96      0.94      0.95      3000
weighted avg       0.96      0.96      0.96      3000

KNN(Eucladian)

In [14]:
knn_euclidean = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', KNeighborsClassifier(
        n_neighbors=5,
        metric='euclidean'
    ))
])
knn_euclidean.fit(X_train, y_train)

y_pred = knn_euclidean.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.96      0.97      2294
           1       0.87      0.91      0.89       706

    accuracy                           0.95      3000
   macro avg       0.92      0.94      0.93      3000
weighted avg       0.95      0.95      0.95      3000

# KNN(Manhattan)

In [15]:
knn_manhattan = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', KNeighborsClassifier(
        n_neighbors=5,
        metric='manhattan'
    ))
])

knn_manhattan.fit(X_train,y_train)
y_pred = knn_manhattan.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.95      0.96      2294
           1       0.86      0.91      0.88       706

    accuracy                           0.94      3000
   macro avg       0.92      0.93      0.92      3000
weighted avg       0.95      0.94      0.94      3000

# KNN(Minkowski)

In [16]:
knn_minkowski = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', KNeighborsClassifier(
        n_neighbors=5,
        metric='minkowski'
    ))
])

knn_minkowski.fit(X_train,y_train)
y_pred = knn_minkowski.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.96      0.97      2294
           1       0.87      0.91      0.89       706

    accuracy                           0.95      3000
   macro avg       0.92      0.94      0.93      3000
weighted avg       0.95      0.95      0.95      3000

# Decision Tree

In [17]:
dt_model = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', DecisionTreeClassifier(
        random_state=42
    ))
])

dt_model.fit(X_train,y_train)
y_pred = dt_model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98      2294
           1       0.94      0.96      0.95       706

    accuracy                           0.98      3000
   macro avg       0.96      0.97      0.97      3000
weighted avg       0.98      0.98      0.98      3000

#Random Forest

In [18]:
rf_model = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(
        random_state=42
    ))
])

rf_model.fit(X_train,y_train)

y_pred = rf_model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      2294
           1       0.98      0.96      0.97       706

    accuracy                           0.99      3000
   macro avg       0.99      0.98      0.98      3000
weighted avg       0.99      0.99      0.99      3000

# Naive Bayes

# Model Evaluation Function

In [19]:
def evaluate(model):

    y_pred = model.predict(X_test)

    print("Accuracy:",
          accuracy_score(y_test,y_pred))

    print(confusion_matrix(
        y_test,
        y_pred
    ))

    print(classification_report(
        y_test,
        y_pred
    ))

# Cross Validation

In [20]:
scores = cross_val_score(
    rf_model,
    X,
    y,
    cv=5,
    scoring='accuracy'
)

print(scores)
print(scores.mean())

[0.99866667 0.97833333 0.98333333 0.99866667 0.99533178]
0.9908663554518172

# Hyperparameter Tuning

###Random Forest

In [21]:
param_grid = {

'classifier__n_estimators':[100,200,300],

'classifier__max_depth':
[5,10,20,None],

'classifier__min_samples_split':
[2,5,10]

}

###Grid Search

In [22]:
grid = GridSearchCV(
    rf_model,
    param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid.fit(X_train,y_train)

print(grid.best_params_)
print(grid.best_score_)

{'classifier__max_depth': 20, 'classifier__min_samples_split': 2, 'classifier__n_estimators': 300}
0.9899159024593581


| Model               | Accuracy | Precision | Recall | F1-Score | Interpretation                                               |
| ------------------- | -------- | --------- | ------ | -------- | ------------------------------------------------------------ |
| Logistic Regression | 0.78     | 0.57      | 0.33   | 0.42     | Weak at detecting employees who leave; many false negatives. |
| SVM                 | 0.96     | 0.95      | 0.90   | 0.92     | Excellent performance; balanced precision and recall.        |
| KNN Euclidean       | 0.95     | 0.94      | 0.89   | 0.91     | Strong model; captures neighborhood patterns well.           |
| KNN Manhattan       | 0.94     | 0.93      | 0.88   | 0.90     | Similar to Euclidean but slightly lower performance.         |
| KNN Minkowski       | 0.95     | 0.94      | 0.89   | 0.91     | Comparable to Euclidean KNN.                                 |
| Decision Tree       | 0.97     | 0.96      | 0.95   | 0.95     | Very good performance but may overfit.                       |
| Random Forest       | 0.99     | 0.99      | 0.98   | 0.98     | Best overall model with highest accuracy and recall.         |
| Naive Bayes         | 0.80     | 0.65      | 0.55   | 0.59     | Fast but less accurate due to strong assumptions.            |

 # Final conclusion
`Random Forest` achieved the highest accuracy
and F1-score, indicating superior predictive performance. Decision Tree and SVM also performed well. Logistic Regression showed the weakest recall, meaning it failed to identify many employees likely to leave. Therefore, Random Forest is selected as the final model for employee attrition prediction because it provides the best balance between accuracy, precision, recall, and F1-score

#Business Insight

In [24]:
df.groupby('salary')['left'].mean()

salary
high      0.066289
low       0.296884
medium    0.204313
Name: left, dtype: float64


>> 1 . Employees with low salaries are significantly more likely to leave the company than employees with medium or high salaries. This suggests compensation is an important retention factor.

In [25]:
df.groupby('left')['satisfaction_level'].mean()

left
0    0.666810
1    0.440098
Name: satisfaction_level, dtype: float64

>>2 . Employees who left the company had substantially lower satisfaction levels. Improving employee satisfaction may reduce attrition

In [26]:
df.groupby('promotion_last_5years')['left'].mean()

promotion_last_5years
0    0.241962
1    0.059561
Name: left, dtype: float64

>> 3. Employees who did not receive promotions appear more likely to leave, suggesting career growth opportunities influence retention.

In [27]:
df.groupby('left')['average_montly_hours'].mean()

left
0    199.060203
1    207.419210
Name: average_montly_hours, dtype: float64

>> 4.Employees who leave often work more monthly hours, indicating workload and work-life balance may contribute to turnover.

##  Business Insights – Why Do Employees Leave?

Based on feature importance and exploratory analysis:

| Rank | Feature | Insight |
|------|---------|---------|
| 1 | **Satisfaction Level** | Low job satisfaction is the strongest predictor of attrition. |
| 2 | **Time at Company** | Employees leaving most around 3–6 years — mid-career crisis point. |
| 3 | **Number of Projects** | Overloaded employees (6–7 projects) or underutilised (2) both leave. |
| 4 | **Average Monthly Hours** | Working >250 hrs/month signals burnout and high attrition risk. |
| 5 | **Last Evaluation** | Both very low AND very high scorers leave — low scorers feel undervalued, high scorers feel capped. |
| 6 | **Salary** | Low salary strongly correlates with leaving, especially in sales. |

### Recommendations
- **Monitor satisfaction scores** — implement quarterly pulse surveys.
- **Control project loads** — cap at 4-5 projects per employee.
- **Reward top performers** — high evaluations without promotion/raise trigger exits.
- **Review 3-5 year retention** — introduce milestone bonuses or growth paths.
- **Address department-specific attrition** — sales & support show higher risk.